<?xml version="1.0"?>
<robot name="op_table"
       xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics">

  <property name="op_table_height" value="0.72" />
  <property name="op_table_width"  value="1.2" />
  <property name="op_table_depth"  value="0.6" />
  <property name="op_leg_radius"   value="0.02" />
  <property name="op_table_x"      value="0.0" />
  <property name="op_table_y"      value="0.0" />
  <property name="op_table_z"      value="0.0" />

  <property name="op_table_top_thickness" value="0.025"/>

  <property name="op_table_top_color" value="0 0 0 1" />
  <property name="op_leg_color" value="0 0 0 1" />

  <property name="M_PI" value="3.1415926535897931" />

  
  <!-- tabletop height is .55+.01+.025=.585 -->
  <link name="op_table_top_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="${op_table_x} ${op_table_y} ${op_table_z+op_table_height-op_table_top_thickness/2}" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial> 
    <visual>
      <origin xyz="${op_table_x} ${op_table_y} ${op_table_z+op_table_height-op_table_top_thickness/2}" />
      <geometry>
        <box size="${op_table_width} ${op_table_depth} ${op_table_top_thickness}" />
      </geometry>
      <material name="op_table_top_grey">
        <color rgba="${op_table_top_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="${op_table_x} ${op_table_y} ${op_table_z+op_table_height-op_table_top_thickness/2}" />
      <geometry>
        <box size="${op_table_width} ${op_table_depth} ${op_table_top_thickness}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="op_table_top_link">
    <material>Gazebo/LightWood</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <joint name="op_leg1_joint" type="fixed" >
    <parent link="op_table_top_link" />
    <origin xyz="${op_table_x+op_table_width/2} ${op_table_y+op_table_depth/2} ${op_table_z+op_table_height}" rpy="0 0 0" />
    <child link="op_leg1_link" />
  </joint> 
  <link name="op_leg1_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-op_table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-op_table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${op_leg_radius}" length="${op_table_height}" />
      </geometry>
      <material name="op_leg1_black">
        <color rgba="${op_leg_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${-op_table_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${op_leg_radius}" length="${op_table_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="op_leg1_link">
    <material>Gazebo/Gray</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="op_leg2_joint" type="fixed" >
    <parent link="op_table_top_link" />
    <origin xyz="${op_table_x-op_table_width/2} ${op_table_y+op_table_depth/2} ${op_table_z+op_table_height}" rpy="0 0 0" />
    <child link="op_leg2_link" />
  </joint> 
  <link name="op_leg2_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-op_table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-op_table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${op_leg_radius}" length="${op_table_height}" />
      </geometry>
      <material name="op_leg2_black">
        <color rgba="${op_leg_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${-op_table_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${op_leg_radius}" length="${op_table_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="op_leg2_link">
    <material>Gazebo/Gray</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="op_leg3_joint" type="fixed" >
    <parent link="op_table_top_link" />
    <origin xyz="${op_table_x+op_table_width/2} ${op_table_y-op_table_depth/2} ${op_table_z+op_table_height}" rpy="0 0 0" />
    <child link="op_leg3_link" />
  </joint> 
  <link name="op_leg3_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-op_table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-op_table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${op_leg_radius}" length="${op_table_height}" />
      </geometry>
      <material name="op_leg3_black">
        <color rgba="${op_leg_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${-op_table_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${op_leg_radius}" length="${op_table_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="op_leg3_link">
    <material>Gazebo/Gray</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="op_leg4_joint" type="fixed" >
    <parent link="op_table_top_link" />
    <origin xyz="${op_table_x-op_table_width/2} ${op_table_y-op_table_depth/2} ${op_table_z+op_table_height}" rpy="0 0 0" />
    <child link="op_leg4_link" />
  </joint> 
  <link name="op_leg4_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-op_table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-op_table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${op_leg_radius}" length="${op_table_height}" />
      </geometry>
      <material name="op_leg4_black">
        <color rgba="${op_leg_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${-op_table_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${op_leg_radius}" length="${op_table_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="op_leg4_link">
    <material>Gazebo/Gray</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

</robot>
